apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cluster-credentials-sanitization
spec:
  description: Returns proper cluster credentials secret name and API URL 
  params:
    - name: cluster-name
      type: string
    - name: kube-api
      type: string
    - name: cluster-credentials
      type: string
  results:
    - name: cluster-credentials
      description: Credentials for the cluster
    - name: kube-api
      description: API URL of the cluster
  steps:
    - computeResources:
        limits:
          cpu: '100m'
          memory: 64Mi
      env:
        - name: WORKSPACE
          value: $(workspaces.shared-workspace.path)
      image: quay.io/kuadrant/testsuite-pipelines-tools:latest
      imagePullPolicy: Always
      name: parameter-sanity-check
      script: |
          #!/usr/bin/env bash
          set -evo pipefail

          # If params are empty use the 'default' values
          if [[ "x$(params.cluster-credentials)" == "x" ]]; then
            if [[ "x$(params.kube-api)" == "x" ]]; then
              echo -n "$(params.cluster-name)-credentials" | tee $(results.cluster-credentials.path)
              printf "%s" "$(cat $(workspaces.shared-workspace.path)/kube-api.txt)" | tee $(results.kube-api.path)
              exit 0
            fi
          fi

          # Just use the parameters as they are if specified
          echo -n "$(params.cluster-credentials)" | tee $(results.cluster-credentials.path)
          echo -n "$(params.kube-api)" | tee $(results.kube-api.path)
  workspaces:
    - name: shared-workspace

