apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: wait-till-osd-is-ready
spec:
  description: 'Wait till OSD is ready'
  params:
    - name: cluster-id
      type: string
  steps:
    - computeResources:
        limits:
          cpu: '100m'
          memory: 64Mi
      image: 'quay.io/trepel/kuadrant-pipelines:latest'
      imagePullPolicy: Always
      name: wait-till-osd-is-ready
      script: |
        #!/usr/bin/env bash
        set -evo pipefail

        # Use ocm.json created by ocm-login Task
        export OCM_CONFIG=$(workspaces.shared-workspace.path)/ocm.json

        # Wait for cluster to become ready
        INTERVAL=60  # Check every 60 seconds
        MAX_ATTEMPTS=60
        echo "Waiting for cluster to become ready, active check each $INTERVAL seconds, max no. of checks is $MAX_ATTEMPTS"

        for ((i=0; i<MAX_ATTEMPTS; i++)); do
            STATE=$(ocm describe cluster $(params.cluster-id) | grep 'State' | awk '{print $2}')
            echo "Current cluster state is $STATE"
            if [ "$STATE" == "ready" ]; then
                echo "Cluster is ready."
                break
            fi
            echo "Waiting for cluster  $(params.cluster-id) to become ready..."
            sleep $INTERVAL
        done

        echo "Either cluster is ready now or max no. of checks has been reached"
      timeout: 1h30m0s
  workspaces:
    - name: shared-workspace

